program ChromaTest;

{FastMM4,
  FastMM4Messages,
  }
uses
  FastMM4,
  FastMM4Messages,
  Forms,
  MainUnit in 'MainUnit.pas' {APITestForm},
  FFTypes in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\FFTypes.pas',
  libavcodec in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavcodec.pas',
  libavcodec_avfft in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavcodec_avfft.pas',
  libavdevice in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavdevice.pas',
  libavfilter in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavfilter.pas',
  libavfilter_avcodec in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavfilter_avcodec.pas',
  libavfilter_buffersink in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavfilter_buffersink.pas',
  libavfilter_buffersrc in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavfilter_buffersrc.pas',
  libavfilter_formats in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavfilter_formats.pas',
  libavformat in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavformat.pas',
  libavformat_avio in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavformat_avio.pas',
  libavformat_url in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavformat_url.pas',
  libavutil in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil.pas',
  libavutil_audio_fifo in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_audio_fifo.pas',
  libavutil_avstring in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_avstring.pas',
  libavutil_bprint in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_bprint.pas',
  libavutil_buffer in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_buffer.pas',
  libavutil_channel_layout in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_channel_layout.pas',
  libavutil_common in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_common.pas',
  libavutil_cpu in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_cpu.pas',
  libavutil_dict in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_dict.pas',
  libavutil_error in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_error.pas',
  libavutil_eval in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_eval.pas',
  libavutil_fifo in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_fifo.pas',
  libavutil_file in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_file.pas',
  libavutil_frame in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_frame.pas',
  libavutil_imgutils in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_imgutils.pas',
  libavutil_log in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_log.pas',
  libavutil_mathematics in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_mathematics.pas',
  libavutil_md5 in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_md5.pas',
  libavutil_mem in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_mem.pas',
  libavutil_motion_vector in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_motion_vector.pas',
  libavutil_opt in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_opt.pas',
  libavutil_parseutils in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_parseutils.pas',
  libavutil_pixdesc in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_pixdesc.pas',
  libavutil_pixfmt in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_pixfmt.pas',
  libavutil_rational in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_rational.pas',
  libavutil_samplefmt in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_samplefmt.pas',
  libavutil_time in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_time.pas',
  libavutil_timestamp in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libavutil_timestamp.pas',
  libswresample in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libswresample.pas',
  libswscale in 'F:\External\ffmpeg-delphi-pascal-headers-2.5.4\headers\libswscale.pas',
  CP.Utils in '..\..\Units\CP.Utils.pas',
  CP.TestUtils in '..\..\Units\CP.TestUtils.pas',
  CP.SilenceRemover in '..\..\Units\CP.SilenceRemover.pas',
  CP.Resampler in '..\..\Units\CP.Resampler.pas',
  CP.Quantizer in '..\..\Units\CP.Quantizer.pas',
  CP.LomontFFT in '..\..\Units\CP.LomontFFT.pas',
  CP.IntegralImage in '..\..\Units\CP.IntegralImage.pas',
  CP.Imagebuilder in '..\..\Units\CP.Imagebuilder.pas',
  CP.Image in '..\..\Units\CP.Image.pas',
  CP.FingerprinterConfiguration in '..\..\Units\CP.FingerprinterConfiguration.pas',
  CP.FingerprintCompressor in '..\..\Units\CP.FingerprintCompressor.pas',
  CP.FingerprintCalculator in '..\..\Units\CP.FingerprintCalculator.pas',
  CP.Fingerprint in '..\..\Units\CP.Fingerprint.pas',
  CP.Filter in '..\..\Units\CP.Filter.pas',
  CP.FFT in '..\..\Units\CP.FFT.pas',
  CP.FeatureVectorConsumer in '..\..\Units\CP.FeatureVectorConsumer.pas',
  CP.Def in '..\..\Units\CP.Def.pas',
  CP.CombinedBuffer in '..\..\Units\CP.CombinedBuffer.pas',
  CP.Classifier in '..\..\Units\CP.Classifier.pas',
  CP.ChromaPrint in '..\..\Units\CP.ChromaPrint.pas',
  CP.Chroma in '..\..\Units\CP.Chroma.pas',
  CP.BitString in '..\..\Units\CP.BitString.pas',
  CP.Base64 in '..\..\Units\CP.Base64.pas',
  CP.AVFFT in '..\..\Units\CP.AVFFT.pas',
  CP.AudioProcessor in '..\..\Units\CP.AudioProcessor.pas',
  CP.AudioConsumer in '..\..\Units\CP.AudioConsumer.pas',
  CP.AudioBuffer in '..\..\Units\CP.AudioBuffer.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.CreateForm(TAPITestForm, APITestForm);
  Application.Run;
end.
